In [1]:
import numpy as np

In [3]:
np.__version__

'1.25.2'

In [5]:
type([1,2,3])

list

In [6]:
arr = np.array([1,2,3])
type(arr)

numpy.ndarray

In [7]:
arr.ndim

1

In [9]:
arr.shape

(3,)

In [10]:
np.mean(arr)

2.0

In [11]:
np.median(arr)

2.0

In [12]:
np.std(arr)

0.816496580927726

In [13]:
x = np.array([
    [1,2,3],[4,5,6]
])

In [14]:
x.ndim

2

In [15]:
x.shape

(2, 3)

In [16]:
x.size

6

In [21]:
## slicing and indexing
arr2 = np.sort(arr)
arr2

array([1, 2, 3])

In [23]:
arr3 = np.array([0,6,5,1,2,3])
arr3

array([0, 6, 5, 1, 2, 3])

In [27]:
sorted_array = np.sort(arr3)
sorted_array

array([0, 1, 2, 3, 5, 6])

In [31]:
sorted_array[-2:]

array([5, 6])

In [52]:
arr2d = np.array([
    [2,3,4],
    [6,7,8]
]
)

In [46]:
arr2d

array([[2, 3, 4],
       [6, 7, 8]])

In [47]:
type(arr2d)

numpy.ndarray

In [48]:
arr2d[0]

array([2, 3, 4])

In [50]:
arr2d[0][0]

2

In [54]:
arry3d =np.array(
    [[[1,2,3],[3,4,6]],
    [[4,5,6],[5,6,8]]]
)

In [57]:
arry3d.ndim

3

## Mini Project 
* Temperature Data Analysis : 
Generate random temperature data for 30 days and calculate the mean, median and standard deviation of the temperature over ten months. ALso, find the days with temperatures above the average.

In [59]:
weather = np.random.uniform(22,38,30)
weather

array([27.03004269, 23.67020584, 26.68432567, 34.47634238, 27.95925366,
       35.89458539, 30.44067626, 29.24965884, 22.71620179, 31.13576194,
       28.34830809, 31.53855072, 29.99844677, 25.84642345, 37.92641115,
       33.31181163, 36.22833704, 24.17915581, 24.46841086, 23.10202667,
       24.7654097 , 32.86601783, 33.54989867, 35.64936354, 26.3637379 ,
       32.48875125, 32.70680056, 25.93889565, 25.32234206, 35.46859934])

In [60]:
# mean
w_mean = np.mean(weather)
w_mean

29.64415843907284

In [61]:
w_median = np.median(weather)
w_median

29.624052804157945

In [62]:
w_std = np.std(weather)
w_std

4.44328500845782

In [64]:
hot_days = weather[weather > w_mean]
hot_days

array([34.47634238, 35.89458539, 30.44067626, 31.13576194, 31.53855072,
       29.99844677, 37.92641115, 33.31181163, 36.22833704, 32.86601783,
       33.54989867, 35.64936354, 32.48875125, 32.70680056, 35.46859934])